#pragma config(Sensor, S1,     touch1,         sensorTouch)
#pragma config(Sensor, S2,     touch2,         sensorTouch)
#pragma config(Sensor, S3,     touch3,         sensorTouch)
#pragma config(Sensor, S4,     touch4,         sensorTouch)
#pragma config(Motor,  motorA,          light1,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          light2,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void touchif(); //1°³ ´©
void touchif2(); //2°³ ´©
void reset_touchcheck(); //SensorValue, touchcheck ¸¦ 0À¸·Î 
void signal1(); //1´Ü°è 
void signal2(); //2´Ü°è 
int touchcheck, signalcheck;

task main()
{
   int levelcount; //123 - 1´Ü°è , 456 - 2´Ü°è, 789 -

   while (1)
   {
			nxtDisplayCenteredBigTextLine(1, "Hello NXT!");
			nxtDisplayCenteredBigTextLine(3, "1. Tutorial");
			nxtDisplayCenteredBigTextLine(4, "2. Play Game");
			nxtDisplayCenteredBigTextLine(5, "3. Exit");
      touchif();
      if (touchcheck == 1)
      {
         displayCenteredBigTextLine(1, "Tutorial");
         displayCenteredTextLine(1, "Touch by light or sound");

         motor[motorA] = 200;
         wait1Msec(500);

         if (SensorValue[S1] == 1)
         {
            // playSound(); ? ?
         }
         else
         {
            // playsound(); A?
         }
         reset_touchcheck();
      }

      else if (touchcheck == 2)
      {
      	levelcount = 1;
        displayCenteredBigTextLine(3, "Play Game");
        //displayClearTextLine();
        wait1Msec(1000);
        while (levelcount < 10) { //Å¸ÀÌ¸Ó ±¸
            if(levelcount < 4) {
               displayCenteredBigTextLine(3, "Level 1");
               signal1();
               touchif();
               clearTimer(T1);
               if (touchcheck == signalcheck && time1[T1] < 3000) {
                  // Á¤´ä 
                  levelcount++;
               }
               else
               {
                  displayCenteredBigTextLine(3, "Game Over");
               		//Æ²¸°
                  break;
               }
            }
            else if(levelcount < 7) {
               if (levelcount == 4) {
                  //´Ü°è¿Ã¶ó°
               }
               displayCenteredBigTextLine(3, "Level 2");
               signal2();
               touchif2();
               clearTimer(T1);
               if (touchcheck == signalcheck && time1[T1] < 2000) {
                  // Á¤´ä 
                  levelcount++;
               }
               else
               {  displayCenteredBigTextLine(3, "Game Over");
               		//game over sound
                  break;
               }
            }
            else if(levelcount > 6) {
               if (levelcount == 7) {
                  //´Ü°è¿Ã¶ó°
               }
               displayCenteredBigTextLine(3, "Level 3");
               signal2();
               touchif2();
               clearTimer(T1);
               if (touchcheck == signalcheck && time1[T1] < 1000) {
                  // Á¤´ä 
                  levelcount++;
               }
               else
               {
                  displayCenteredBigTextLine(3, "Game Over");
               		//game over sound
                  break;
               }
             }
            reset_touchcheck();
         }
         displayCenteredBigTextLine(3, "Game Clear");
         //playsound - Å¬¸
      }
      else if(touchcheck == 3){
      displayCenteredBigTextLine(3, "Bye Bye~");
      break;
      }

   }
}



void touchif()
{
    if (SensorValue[S1] == 1 && SensorValue[S2] == 0 && SensorValue[S3] == 0 && SensorValue[S4] == 0)
    {
        touchcheck = 1;
    }
    else if (SensorValue[S2] == 1 && SensorValue[S1] == 0 && SensorValue[S3] == 0 && SensorValue[S4] == 0)
    {
        touchcheck = 2;
    }
    else if (SensorValue[S3] == 1 && SensorValue[S1] == 0 && SensorValue[S2] == 0 && SensorValue[S4] == 0)
    {
        touchcheck = 3;
    }
    else if (SensorValue[S4] == 1 && SensorValue[S1] == 0 && SensorValue[S2] == 0 && SensorValue[S3] == 0)
    {
        touchcheck = 4;
    }
    else //¾È´­·
        touchcheck = 0;
}

void touchif2() {
    if (SensorValue[S1] == 1 && SensorValue[S2] == 1 && SensorValue[S3] == 0 && SensorValue[S4] == 0)
    {
        touchcheck = 1;
    }
    else if (SensorValue[S1] == 1 && SensorValue[S3] == 1 && SensorValue[S2] == 0 && SensorValue[S4] == 0)
    {
        touchcheck = 2;
    }
    else if (SensorValue[S1] == 1 && SensorValue[S4] == 1 && SensorValue[S2] == 0 && SensorValue[S3] == 0)
    {
        touchcheck = 3;
    }
    else if (SensorValue[S2] == 1 && SensorValue[S3] == 1 && SensorValue[S1] == 0 && SensorValue[S4] == 0)
    {
        touchcheck = 4;
    }
    else if (SensorValue[S2] == 1 && SensorValue[S4] == 1 && SensorValue[S1] == 0 && SensorValue[S3] == 0)
    {
        touchcheck = 5;
    }
    else if (SensorValue[S3] == 1 && SensorValue[S4] == 1 && SensorValue[S1] == 0 && SensorValue[S2] == 0)
    {
        touchcheck = 6;
    }
    else //¾È´­·
        touchcheck = 0;
}

void reset_touchcheck() {
   touchcheck = 0;
}

void signal1()
{
   int number = random(4);
   switch (number) {
   case 1:
      signalcheck = 1;
      motor[motorA] = 200;
      wait1Msec(500);
      break;

   case 2:
      signalcheck = 2;
      motor[motorB] = 200;
      wait1Msec(500);
      break;

   case 3:
      signalcheck = 3;
      //playsound
      break;

   case 4:
      signalcheck = 4;
      //platsound
      break;
   }
}

void signal2() {
   int number1 = random(4);
   int number2 = random(4);
   while (number1 == number2) {
      number2 = random(4);
   }

   if (number1 == 1 && number2 == 2 || number1 == 2 && number2 == 1) {
      signalcheck = 1;
      motor[motorA] = 200;
      motor[motorB] = 200;
      wait1Msec(500);
   }
   else if (number1 == 1 && number2 == 3 || number1 == 3 && number2 == 1) {
      signalcheck = 2;
      motor[motorA] = 200;
      //playsound - 3¹ø¼
      wait1Msec(500);
   }
   else if (number1 == 1 && number2 == 4 || number1 == 4 && number2 == 1) {
      signalcheck = 3;
      motor[motorA] = 200;
      //playsound - 4¹ø¼
      wait1Msec(500);
   }
   else if (number1 == 2 && number2 == 3 || number1 == 3 && number2 == 2) {
      signalcheck = 4;
      motor[motorB] = 200;
      //playsound - 3¹ø¼
      wait1Msec(500);
   }
   else if (number1 == 2 && number2 == 4 || number1 == 4 && number2 == 2) {
      signalcheck = 5;
      motor[motorB] = 200;
      //palysound - 4¹ø¼
      wait1Msec(500);
   }
   else if (number1 == 3 && number2 == 4 || number1 == 4 && number2 == 3) {
      signalcheck = 6;
      //playsound - 3¹ø¼
      //playsound - 4¹ø¼
   }
}
